In [3]:
import numpy as np
import pandas as pd
import os

In [4]:
arr = np.array([12,34,59,10,30,19,24])

In [5]:
np.argsort(arr) #index number

array([3, 0, 5, 6, 4, 1, 2])

In [6]:
arr[np.argsort(arr)] #once you giving index your data will be sorted

array([10, 12, 19, 24, 30, 34, 59])

In [7]:
#Pandas - A Data Analysis Package

In [8]:
pd?

Type:        module
String form: <module 'pandas' from '/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/pandas/__init__.py'>
File:        /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/pandas/__init__.py
Docstring:
pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

In [9]:
#Pandas Data Structure:
#Series : A one-dimensional array which can hold any kind of data. (column)
#DataFrame : Combination of rows and columns

In [10]:
sr = pd.Series([10,30,50,"A","B","C"], name = "data")

In [11]:
sr

0    10
1    30
2    50
3     A
4     B
5     C
Name: data, dtype: object

In [12]:
# Rows : Index
# Cols : Series

In [13]:
employeedb = {"Emp Name" : ["Abhishek","Ajeet","Ram","Sonu","Soumya"],
              "City" : ["Goa","Chennai","Delhi","Noida","Mumbai"],
              "Salary" : [25000,34000,50000,80000,90000]
             }

In [14]:
df= pd.DataFrame(employeedb)

In [15]:
df

   Emp Name     City  Salary
0  Abhishek      Goa   25000
1     Ajeet  Chennai   34000
2       Ram    Delhi   50000
3      Sonu    Noida   80000
4    Soumya   Mumbai   90000

In [16]:
type(df)

pandas.DataFrame

In [17]:
df['Emp Name']

0    Abhishek
1       Ajeet
2         Ram
3        Sonu
4      Soumya
Name: Emp Name, dtype: str

In [18]:
type(df['Emp Name'])

pandas.Series

In [19]:
os.getcwd() # get current working directory

'/Users/mohitgupta/Downloads/Anu- Data analytics/python-learning'

In [20]:
os.listdir()

['anu_numpy.ipynb',
 'breast_cancer.txt',
 'anu_panda.ipynb',
 'data_numpy_test.py',
 'ai_job_trends_dataset.csv',
 'Untitled1.ipynb',
 '.DS_Store',
 'untitled.md',
 'Store Data (2).xlsx',
 'evng (1).ipynb',
 'Superstore.xlsx',
 '.ipynb_checkpoints',
 'iris 2.json',
 '.~Store Data (2).xlsx']

In [21]:
#Reading a csv

In [22]:
df = pd.read_csv("ai_job_trends_dataset.csv")

In [23]:
# display the data
df.head() # using head we can have a look of first 5 records by default

,Job Title,Industry,Job Status,AI Impact Level,Median Salary (USD),Required Education,Experience Required (Years),Job Openings (2024),Projected Openings (2030),Remote Work Ratio (%),Automation Risk (%),Location,Gender Diversity (%)
0,Investment analyst,IT,Increasing,Moderate,42109.76,Master Degree,5,1515,6342,55.96,28.28,UK,44.63
1,"Journalist, newspaper",Manufacturing,Increasing,Moderate,132298.57,Master Degree,15,1243,6205,16.81,89.71,USA,66.39
2,Financial planner,Finance,Increasing,Low,143279.19,Bachelor Degree,4,3338,1154,91.82,72.97,Canada,41.13
3,Legal secretary,Healthcare,Increasing,High,97576.13,Associate Degree,15,7173,4060,1.89,99.94,Australia,65.76
4,Aeronautical engineer,IT,Increasing,Low,60956.63,Master Degree,13,5944,7396,53.76,37.65,Germany,72.57

In [24]:
df.head(3)

,Job Title,Industry,Job Status,AI Impact Level,Median Salary (USD),Required Education,Experience Required (Years),Job Openings (2024),Projected Openings (2030),Remote Work Ratio (%),Automation Risk (%),Location,Gender Diversity (%)
0,Investment analyst,IT,Increasing,Moderate,42109.76,Master Degree,5,1515,6342,55.96,28.28,UK,44.63
1,"Journalist, newspaper",Manufacturing,Increasing,Moderate,132298.57,Master Degree,15,1243,6205,16.81,89.71,USA,66.39
2,Financial planner,Finance,Increasing,Low,143279.19,Bachelor Degree,4,3338,1154,91.82,72.97,Canada,41.13

In [25]:
#Reading an excel

In [26]:
Import openpyxl

SyntaxError: invalid syntax (1364750621.py, line 1)

In [30]:
superstore.head(2)

NameError: name 'superstore' is not defined

In [ ]:
##  Reading the data from text file

In [31]:
df = pd.read_csv("breast_cancer.txt")

In [32]:
df.head(3)

,id,clump_thickness,unif_cell_size,uniform_cell_shape,marginal_adhesion,single_epi_cell_size,bare_nuclei,bland_chromation,normal_nucleoli,mitoses,class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2

In [ ]:
# reading json

In [33]:
json = pd.read_json("iris 2.json")

In [34]:
json.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [35]:
df = pd.read_clipboard()

In [36]:
df

Empty DataFrame
Columns: [#, give, me, the, columns]
Index: []

In [ ]:
#DataFrame Operations
#__Add blockquote

In [37]:
df = pd.read_csv("ai_job_trends_dataset.csv")

In [38]:
df.head(2)

,Job Title,Industry,Job Status,AI Impact Level,Median Salary (USD),Required Education,Experience Required (Years),Job Openings (2024),Projected Openings (2030),Remote Work Ratio (%),Automation Risk (%),Location,Gender Diversity (%)
0,Investment analyst,IT,Increasing,Moderate,42109.76,Master Degree,5,1515,6342,55.96,28.28,UK,44.63
1,"Journalist, newspaper",Manufacturing,Increasing,Moderate,132298.57,Master Degree,15,1243,6205,16.81,89.71,USA,66.39

In [39]:
df.shape

(30000, 13)

In [40]:
print(f"number of rows:{df.shape[0]} and colums:{df.shape[-1]}")

number of rows:30000 and colums:13

In [41]:
df.tail() # this function display bottom 5 recs by default

,Job Title,Industry,Job Status,AI Impact Level,Median Salary (USD),Required Education,Experience Required (Years),Job Openings (2024),Projected Openings (2030),Remote Work Ratio (%),Automation Risk (%),Location,Gender Diversity (%)
29995,"Psychotherapist, dance movement",Education,Increasing,Moderate,142238.00,PhD,16,7816,1363,56.91,27.27,China,65.90
29996,"Scientist, water quality",IT,Decreasing,Moderate,123107.50,Associate Degree,19,9358,7632,27.25,12.84,UK,31.18
29997,Web designer,Manufacturing,Decreasing,Moderate,97305.51,Master Degree,0,9605,2559,31.76,16.82,China,26.07
29998,Primary school teacher,Entertainment,Increasing,Moderate,95599.22,High School,15,5481,4879,32.46,45.93,Brazil,40.43
29999,Company secretary,Education,Increasing,Low,65679.61,High School,15,4435,5902,34.54,78.93,Germany,21.75

In [42]:
df

,Job Title,Industry,Job Status,AI Impact Level,Median Salary (USD),Required Education,Experience Required (Years),Job Openings (2024),Projected Openings (2030),Remote Work Ratio (%),Automation Risk (%),Location,Gender Diversity (%)
0,Investment analyst,IT,Increasing,Moderate,42109.76,Master Degree,5,1515,6342,55.96,28.28,UK,44.63
1,"Journalist, newspaper",Manufacturing,Increasing,Moderate,132298.57,Master Degree,15,1243,6205,16.81,89.71,USA,66.39
2,Financial planner,Finance,Increasing,Low,143279.19,Bachelor Degree,4,3338,1154,91.82,72.97,Canada,41.13
3,Legal secretary,Healthcare,Increasing,High,97576.13,Associate Degree,15,7173,4060,1.89,99.94,Australia,65.76
4,Aeronautical engineer,IT,Increasing,Low,60956.63,Master Degree,13,5944,7396,53.76,37.65,Germany,72.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,"Psychotherapist, dance movement",Education,Increasing,Moderate,142238.00,PhD,16,7816,1363,56.91,27.27,China,65.90
29996,"Scientist, water quality",IT,Decreasing,Moderate,123107.50,Associate Degree,19,9358,7632,27.25,12.84,UK,31.18
29997,Web designer,Manufacturing,Decreasing,Moderate,97305.51,Master Degree,0,9605,2559,31.76,16.82,China,26.07
29998,Primary school teacher,Entertainment,Increasing,Moderate,95599.22,High School,15,5481,4879,32.46,45.93,Brazil,40.43
29999,Company secretary,Education,Increasing,Low,65679.61,High School,15,4435,5902,34.54,78.93,Germany,21.75

In [ ]:
# give me the columns

In [43]:
df.columns

Index(['Job Title', 'Industry', 'Job Status', 'AI Impact Level',
       'Median Salary (USD)', 'Required Education',
       'Experience Required (Years)', 'Job Openings (2024)',
       'Projected Openings (2030)', 'Remote Work Ratio (%)',
       'Automation Risk (%)', 'Location', 'Gender Diversity (%)'],
      dtype='str')

In [44]:
df.keys()

Index(['Job Title', 'Industry', 'Job Status', 'AI Impact Level',
       'Median Salary (USD)', 'Required Education',
       'Experience Required (Years)', 'Job Openings (2024)',
       'Projected Openings (2030)', 'Remote Work Ratio (%)',
       'Automation Risk (%)', 'Location', 'Gender Diversity (%)'],
      dtype='str')

In [45]:
df.columns.to_list()

['Job Title',
 'Industry',
 'Job Status',
 'AI Impact Level',
 'Median Salary (USD)',
 'Required Education',
 'Experience Required (Years)',
 'Job Openings (2024)',
 'Projected Openings (2030)',
 'Remote Work Ratio (%)',
 'Automation Risk (%)',
 'Location',
 'Gender Diversity (%)']

In [ ]:
# can you display Industry column

In [47]:
df['Industry']

0                   IT
1        Manufacturing
2              Finance
3           Healthcare
4                   IT
             ...
29995        Education
29996               IT
29997    Manufacturing
29998    Entertainment
29999        Education
Name: Industry, Length: 30000, dtype: str

In [48]:
df['Industry'].unique()

<StringArray>
[            'IT',  'Manufacturing',        'Finance',     'Healthcare',
      'Education',  'Entertainment',         'Retail', 'Transportation']
Length: 8, dtype: str

In [49]:
df['Industry'].nunique() # number of unique

8

In [54]:
df[['Job Title','Industry','Location']].head(1) #one way to find perticular colums

            Job Title Industry Location
0  Investment analyst       IT       UK

In [56]:
df.head(1)

,Job Title,Industry,Job Status,AI Impact Level,Median Salary (USD),Required Education,Experience Required (Years),Job Openings (2024),Projected Openings (2030),Remote Work Ratio (%),Automation Risk (%),Location,Gender Diversity (%)
0,Investment analyst,IT,Increasing,Moderate,42109.76,Master Degree,5,1515,6342,55.96,28.28,UK,44.63

In [51]:
cols = ['Job Title','Industry','Location'] #this is another way to find perticular colms

In [52]:
df[cols]

                             Job Title       Industry   Location
0                   Investment analyst             IT         UK
1                Journalist, newspaper  Manufacturing        USA
2                    Financial planner        Finance     Canada
3                      Legal secretary     Healthcare  Australia
4                Aeronautical engineer             IT    Germany
...                                ...            ...        ...
29995  Psychotherapist, dance movement      Education      China
29996         Scientist, water quality             IT         UK
29997                     Web designer  Manufacturing      China
29998           Primary school teacher  Entertainment     Brazil
29999                Company secretary      Education    Germany

[30000 rows x 3 columns]

In [53]:
df[cols].head(2)

               Job Title       Industry Location
0     Investment analyst             IT       UK
1  Journalist, newspaper  Manufacturing      USA

In [63]:
sales = pd.read_excel('Superstore.xlsx')

In [64]:
sales.shape

(9994, 21)

In [62]:
!pip3 install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]━━ 1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip

In [65]:
sales.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [66]:
sales.shape

(9994, 21)

In [67]:
sales.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [68]:
pd.set_option('display.max_rows',None)

In [70]:
#sales

In [72]:
pd.set_option('display.max_columns',None)

In [73]:
sales.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,12/06/16,16/06/16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [76]:
#pd.reset_option('all')

In [83]:
pd.reset_option('display.max_columns')

In [84]:
sales.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [85]:
sales['Sub-Category']

0         Bookcases
1            Chairs
2            Labels
3            Tables
4           Storage
           ...
9989    Furnishings
9990    Furnishings
9991         Phones
9992          Paper
9993     Appliances
Name: Sub-Category, Length: 9994, dtype: str

In [86]:
sales['Sub-Category'].value_counts()

Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [ ]:
# how we can delete the data(column) from tha dataframe

In [87]:
sales.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [88]:
df = sales.copy()

In [90]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [ ]:
#DataFrame Drop
Using this function we can drop any specific rows by default, however we can drop a specific columns as well 
but we need to define the axis. You can define the axis such as, axis = 1, axis = "columns

In [91]:
df.drop("Row ID",inplace = True, axis = 1) # axis = 1 -> columns, axis = 0 -> rows

In [92]:
df.head(2)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [93]:
# more than 1 columns
df.drop(["Postal Code","Product ID"],axis = "columns").head(1)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136

In [94]:
df.drop(["Postal Code","Product ID"],inplace = True,axis = "columns") #inplace means jo function lga h permanentaly apply ho

In [96]:
df.head(2)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,CA-2016-152156,08/11/16,11/11/16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [97]:
cols = ['Ship Date','Customer ID','Product Name','Discount','Country']

In [98]:
df.drop(columns=cols,inplace = True)

In [99]:
df.head(2)

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,CA-2016-152156,08/11/16,Second Class,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261.96,2,41.9136
1,CA-2016-152156,08/11/16,Second Class,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731.94,3,219.5820

In [ ]:
#How to sort and Filter the data?

In [100]:
df.sort_values(by = "Customer Name", ascending=False)

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
5897,CA-2016-167682,03/04/16,Standard Class,Zuschuss Donatelli,Consumer,Richmond,Indiana,Central,Furniture,Furnishings,71.120,4,22.0472
20,CA-2014-143336,27/08/14,Second Class,Zuschuss Donatelli,Consumer,San Francisco,California,West,Office Supplies,Binders,22.720,4,7.3840
19,CA-2014-143336,27/08/14,Second Class,Zuschuss Donatelli,Consumer,San Francisco,California,West,Technology,Phones,213.480,3,16.0110
3815,CA-2016-152471,08/07/16,Same Day,Zuschuss Donatelli,Consumer,Jacksonville,Florida,South,Office Supplies,Paper,15.984,2,4.9950
8341,CA-2017-141481,11/06/17,First Class,Zuschuss Donatelli,Consumer,Los Angeles,California,West,Office Supplies,Appliances,61.440,3,16.5888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8222,CA-2014-152905,18/02/14,Standard Class,Aaron Bergman,Consumer,Arlington,Texas,Central,Office Supplies,Storage,12.624,2,-2.5248
4961,CA-2014-156587,07/03/14,First Class,Aaron Bergman,Consumer,Seattle,Washington,West,Furniture,Chairs,48.712,1,5.4801
8801,CA-2016-140935,10/11/16,First Class,Aaron Bergman,Consumer,Oklahoma City,Oklahoma,Central,Technology,Phones,221.980,2,62.1544
8802,CA-2016-140935,10/11/16,First Class,Aaron Bergman,Consumer,Oklahoma City,Oklahoma,Central,Furniture,Bookcases,341.960,2,54.7136
4962,CA-2014-156587,07/03/14,First Class,Aaron Bergman,Consumer,Seattle,Washington,West,Office Supplies,Art,17.940,3,4.6644

In [104]:
df.sort_values(by = ["Customer Name","Sales"], ascending=False).head()

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
3814,CA-2016-152471,08/07/16,Same Day,Zuschuss Donatelli,Consumer,Jacksonville,Florida,South,Technology,Phones,823.96,5,51.4975
5898,CA-2016-167682,03/04/16,Standard Class,Zuschuss Donatelli,Consumer,Richmond,Indiana,Central,Technology,Phones,259.96,4,124.7808
19,CA-2014-143336,27/08/14,Second Class,Zuschuss Donatelli,Consumer,San Francisco,California,West,Technology,Phones,213.48,3,16.0110
5897,CA-2016-167682,03/04/16,Standard Class,Zuschuss Donatelli,Consumer,Richmond,Indiana,Central,Furniture,Furnishings,71.12,4,22.0472
8341,CA-2017-141481,11/06/17,First Class,Zuschuss Donatelli,Consumer,Los Angeles,California,West,Office Supplies,Appliances,61.44,3,16.5888

In [ ]:
#Filter

In [105]:
df.head()

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,CA-2016-152156,08/11/16,Second Class,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261.9600,2,41.9136
1,CA-2016-152156,08/11/16,Second Class,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731.9400,3,219.5820
2,CA-2016-138688,12/06/16,Second Class,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Labels,14.6200,2,6.8714
3,US-2015-108966,11/10/15,Standard Class,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,957.5775,5,-383.0310
4,US-2015-108966,11/10/15,Standard Class,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,22.3680,2,2.5164

In [108]:
df['Ship Mode'] == 'Same Day'

0       False
1       False
2       False
3       False
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Name: Ship Mode, Length: 9994, dtype: bool

In [109]:
sum(df['Ship Mode'] == 'Same Day')

543

In [110]:
df[df['Ship Mode'] == 'Same Day']

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
366,CA-2016-155516,21/10/16,Same Day,Michael Kennedy,Corporate,Manchester,Connecticut,East,Office Supplies,Binders,23.200,4,10.4400
367,CA-2016-155516,21/10/16,Same Day,Michael Kennedy,Corporate,Manchester,Connecticut,East,Office Supplies,Supplies,7.360,2,0.1472
368,CA-2016-155516,21/10/16,Same Day,Michael Kennedy,Corporate,Manchester,Connecticut,East,Office Supplies,Storage,104.790,7,29.3412
369,CA-2016-155516,21/10/16,Same Day,Michael Kennedy,Corporate,Manchester,Connecticut,East,Furniture,Bookcases,1043.920,4,271.4192
657,US-2016-156097,19/09/16,Same Day,Eugene Hildebrand,Home Office,Aurora,Illinois,Central,Furniture,Chairs,701.372,2,-50.0980
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9871,CA-2017-146269,06/10/17,Same Day,Mark Hamilton,Consumer,Chicago,Illinois,Central,Office Supplies,Storage,290.336,2,32.6628
9872,CA-2017-146269,06/10/17,Same Day,Mark Hamilton,Consumer,Chicago,Illinois,Central,Office Supplies,Art,19.152,2,1.1970
9928,CA-2016-129630,04/09/16,Same Day,Ionia McGrath,Consumer,San Francisco,California,West,Furniture,Furnishings,24.270,3,8.7372
9929,CA-2016-129630,04/09/16,Same Day,Ionia McGrath,Consumer,San Francisco,California,West,Technology,Copiers,2799.960,5,944.9865
9963,CA-2015-143700,26/07/15,Same Day,Alan Shonely,Consumer,Philadelphia,Pennsylvania,East,Office Supplies,Paper,10.368,2,3.6288

In [116]:
df[df['Ship Mode'] == 'Same Day'].to_csv("Same_Day.csv", index = False)

In [117]:
df.head(2)

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,CA-2016-152156,08/11/16,Second Class,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261.96,2,41.9136
1,CA-2016-152156,08/11/16,Second Class,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731.94,3,219.5820

In [118]:
df[(df['Segment'] == "Consumer") | (df['Segment'] == "Corporate")].head(2) # | -> or, & -> and

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,CA-2016-152156,08/11/16,Second Class,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,261.96,2,41.9136
1,CA-2016-152156,08/11/16,Second Class,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Chairs,731.94,3,219.5820

In [ ]:
# sub: binders, segment : consumer, sales : >500

In [119]:
(df['Sub-Category'] == "Binders") & (df['Segment'] == "Consumer") & (df['Sales'] > 500)

0       False
1       False
2       False
3       False
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Length: 9994, dtype: bool

In [120]:
sum((df['Sub-Category'] == "Binders") & (df['Segment'] == "Consumer") & (df['Sales'] > 500))

44

In [121]:
df[(df['Sub-Category'] == "Binders") & (df['Segment'] == "Consumer") & (df['Sales'] > 500)]

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
509,CA-2015-145352,16/03/15,Standard Class,Christopher Martinez,Consumer,Atlanta,Georgia,South,Office Supplies,Binders,6354.950,5,3177.4750
1199,CA-2016-130946,08/04/16,Standard Class,Zuschuss Carroll,Consumer,Houston,Texas,Central,Office Supplies,Binders,1088.792,4,-1850.9464
1582,CA-2015-131338,09/08/15,First Class,Naresj Patel,Consumer,New York City,New York,East,Office Supplies,Binders,1217.568,2,456.5880
1896,CA-2017-141789,03/10/17,First Class,Amy Cox,Consumer,Minneapolis,Minnesota,Central,Office Supplies,Binders,1793.980,2,843.1706
1898,CA-2014-169775,29/08/14,Second Class,Ryan Akin,Consumer,Miami,Florida,South,Office Supplies,Binders,505.176,4,-336.7840
2229,CA-2014-128055,31/03/14,Standard Class,Alex Avila,Consumer,San Francisco,California,West,Office Supplies,Binders,673.568,2,252.5880
2239,CA-2016-146633,15/11/16,Second Class,Toby Gnade,Consumer,Los Angeles,California,West,Office Supplies,Binders,1016.792,1,381.2970
2993,CA-2017-147291,11/03/17,Standard Class,Max Jones,Consumer,Detroit,Michigan,Central,Office Supplies,Binders,895.920,4,421.0824
3324,CA-2014-165309,11/11/14,Standard Class,Karen Daniels,Consumer,Houston,Texas,Central,Office Supplies,Binders,896.990,5,-1480.0335
3459,CA-2017-136448,16/09/17,First Class,Adam Shillingsburg,Consumer,Philadelphia,Pennsylvania,East,Office Supplies,Binders,538.194,2,-412.6154
3628,CA-2014-169726,09/08/14,Standard Class,Joseph Holt,Consumer,Seattle,Washington,West,Office Supplies,Binders,2060.744,7,643.9825
3848,CA-2017-161053,22/09/17,First Class,Joel Eaton,Consumer,Fayetteville,Arkansas,South,Office Supplies,Binders,691.960,4,318.3016
4098,CA-2014-116904,23/09/14,Standard Class,Sanjit Chand,Consumer,Minneapolis,Minnesota,Central,Office Supplies,Binders,9449.950,5,4630.4755
4115,CA-2016-163573,24/11/16,First Class,Amy Cox,Consumer,Seattle,Washington,West,Office Supplies,Binders,1219.960,5,381.2375
4163,CA-2015-163587,14/03/15,Standard Class,Emily Phan,Consumer,Dover,New Hampshire,East,Office Supplies,Binders,671.940,3,315.8118
4283,CA-2014-103100,20/12/14,First Class,Adrian Barton,Consumer,Indianapolis,Indiana,Central,Office Supplies,Binders,1103.970,3,496.7865
4355,CA-2015-155600,04/12/15,Second Class,Rose O'Brian,Consumer,Clarksville,Tennessee,South,Office Supplies,Binders,1598.058,7,-1065.3720
4497,CA-2017-155075,02/12/17,Standard Class,Giulietta Weimer,Consumer,Philadelphia,Pennsylvania,East,Office Supplies,Binders,631.176,4,-462.8624
4707,CA-2017-138149,29/06/17,First Class,William Brown,Consumer,Los Angeles,California,West,Office Supplies,Binders,895.920,5,302.3730
4866,CA-2017-122490,13/11/17,Standard Class,Ted Trevino,Consumer,Seattle,Washington,West,Office Supplies,Binders,563.024,11,190.0206
5310,CA-2017-131254,19/11/17,First Class,Nathan Cano,Consumer,Houston,Texas,Central,Office Supplies,Binders,1525.188,6,-2287.7820
5439,CA-2016-167115,04/04/16,Standard Class,Evan Henry,Consumer,New York City,New York,East,Office Supplies,Binders,588.784,2,183.9950
5990,US-2017-163300,15/09/17,Standard Class,Erica Smith,Consumer,Los Angeles,California,West,Office Supplies,Binders,2357.488,7,884.0580
6234,US-2017-142188,11/09/17,Same Day,Jennifer Ferguson,Consumer,Seattle,Washington,West,Office Supplies,Binders,1471.960,5,459.9875
6520,CA-2017-138289,16/01/17,Second Class,Andy Reiter,Consumer,Jackson,Michigan,Central,Office Supplies,Binders,5443.960,4,2504.2216
6534,CA-2014-128209,17/11/14,Standard Class,Greg Tran,Consumer,Buffalo,New York,East,Office Supplies,Binders,2152.776,3,726.5619
6817,CA-2014-144414,17/06/14,Standard Class,Gary Hwang,Consumer,Seattle,Washington,West,Office Supplies,Binders,3266.376,3,1061.5722
7280,CA-2015-162782,21/02/15,Standard Class,Pierre Wener,Consumer,Columbia,Maryland,East,Office Supplies,Binders,2541.980,2,1270.9900
7617,CA-2016-144309,10/12/16,Standard Class,Chris McAfee,Consumer,Watertown,New York,East,Office Supplies,Binders,679.960,5,220.9870
7898,CA-2017-128363,13/08/17,Standard Class,Dan Campbell,Consumer,Memphis,Tennessee,South,Office Supplies,Binders,1614.582,6,-1237.8462
8012,CA-2017-120168,25/05/17,Same Day,Trudy Brown,Consumer,New York City,New York,East,Office Supplies,Binders,663.920,5,207.4750
8208,CA-2015-141565,20/09/15,Standard Class,Barry Gonzalez,Consumer,Nashville,Tennessee,South,Office Supplies,Binders,1369.764,6,-913.1760
8632,CA-2016-107783,28/07/16,First Class,Olvera Toch,Consumer,Bethlehem,Pennsylvania,East,Office Supplies,Binders,1369.764,6,-913.1760
8749,US-2015-163825,16/06/15,First Class,Lena Creighton,Consumer,New York City,New York,East,Office Supplies,Binders,3050.376,3,1143.8910
8832,CA-2015-153423,22/06/15,Standard Class,Shaun Weien,Consumer,Rochester,New York,East,Office Supplies,Binders,1217.568,2,456.5880
9033,CA-2014-152268,02/09/14,Standard Class,Sanjit Chand,Consumer,Fayetteville,Arkansas,South,Office Supplies,Binders,1793.980,2,843.1706
9039,CA-2016-117121,17/12/16,Standard Class,Adrian Barton,Consumer,Detroit,Michigan,Central,Office Supplies,Binders,9892.740,13,4946.3700
9231,CA-2014-148383,27/12/14,Standard Class,Resi Pölking,Consumer,Phoenix,Arizona,West,Office Supplies,Binders,946.764,6,-694.2936
9270,US-2017-102183,21/08/17,Standard Class,Pete Kriz,Consumer,New York City,New York,East,Office Supplies,Binders,4305.552,6,1453.1238
9273,CA-2017-146983,02/09/17,Standard Class,Alan Hwang,Consumer,Henderson,Kentucky,South,Office Supplies,Binders,1577.940,3,757.4112
9490,CA-2017-111738,03/01/17,Standard Class,Christopher Martinez,Consumer,San Francisco,California,West,Office Supplies,Binders,2022.272,8,682.5168
9774,CA-2014-169019,26/07/14,Standard Class,Luke Foster,Consumer,San Antonio,Texas,Central,Office Supplies,Binders,2177.584,8,-3701.8928
9781,CA-2016-153178,14/09/16,Standard Class,Clay Ludtke,Consumer,Long Beach,New York,East,Office Supplies,Binders,673.568,2,252.5880
9968,CA-2017-153871,11/12/17,Standard Class,Richard Bierner,Consumer,Plainfield,New Jersey,East,Office Supplies,Binders,735.980,2,331.1910

In [ ]:
#Can you Save all the sub_category wise data into the csv

In [122]:
df['Sub-Category'].unique()

<StringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

In [123]:
for subcat in df['Sub-Category'].unique():
    rs = df[df['Sub-Category'] == subcat]
    rs.to_csv(subcat + ".csv", index = False)

In [128]:
Anu = df[df['Sub-Category']=="Phones"]

In [129]:
Anu.to_csv("Anu.csv",index=False)

In [124]:
for subcat in df['Sub-Category'].unique():
    df[df['Sub-Category'] == subcat].to_csv(subcat + ".csv", index = False)

In [130]:
for subcat in df['Sub-Category'].unique():
    rs = df[df['Sub-Category'] == subcat]
    rs.to_csv(subcat + ".xls", index = False)

In [132]:
df[df['Customer Name'].str.startswith("A")]

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
12,CA-2017-114412,15/04/17,Standard Class,Andrew Allen,Consumer,Concord,North Carolina,South,Office Supplies,Phones,15.552,3,5.4432
17,CA-2014-167164,13/05/14,Second Class,Alejandro Grove,Consumer,West Jordan,Utah,West,Office Supplies,Phones,55.500,2,9.9900
124,US-2014-152030,26/12/14,Second Class,Alan Dominguez,Home Office,Houston,Texas,Central,Furniture,Phones,600.558,3,-8.5794
187,CA-2016-157000,16/07/16,Standard Class,Alice McCarthy,Corporate,Grand Prairie,Texas,Central,Office Supplies,Phones,37.224,3,3.7224
188,CA-2016-157000,16/07/16,Standard Class,Alice McCarthy,Corporate,Grand Prairie,Texas,Central,Office Supplies,Phones,20.016,3,6.2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9975,US-2016-103674,06/12/16,Standard Class,Anne Pryor,Home Office,Los Angeles,California,West,Office Supplies,Phones,13.360,2,6.4128
9976,US-2016-103674,06/12/16,Standard Class,Anne Pryor,Home Office,Los Angeles,California,West,Technology,Phones,249.584,2,31.1980
9977,US-2016-103674,06/12/16,Standard Class,Anne Pryor,Home Office,Los Angeles,California,West,Office Supplies,Phones,13.860,7,0.0000
9978,US-2016-103674,06/12/16,Standard Class,Anne Pryor,Home Office,Los Angeles,California,West,Office Supplies,Phones,13.376,4,4.6816
9979,US-2016-103674,06/12/16,Standard Class,Anne Pryor,Home Office,Los Angeles,California,West,Office Supplies,Phones,437.472,14,153.1152

In [131]:
df[df['Customer Name'].str.startswith("A")].to_csv("Customer_A.csv", index = False)

In [134]:
df[df['Customer Name'].str.contains("er")]['Customer Name'].unique()

<StringArray>
[    'Lena Hernandez',      'Darren Powers',    'Ted Butterfield',
       'Kunst Miller',  'Henry MacAllister', 'Christopher Schild',
       'Roger Barcio',   'Katherine Ducich',   'Jonathan Doherty',
       'Chad Sievert',
 ...
  'Georgia Rosenberg',        'Tom Stivers',     'Monica Federle',
      'Aaron Bergman',         'Don Miller',      'Mark Haberlin',
      'Theresa Coyne',     'Anemone Ratner',     'Fred Wasserman',
    'Ricardo Emerson']
Length: 160, dtype: str

In [136]:
df[df['Customer Name'].str.endswith("h")].head(4)

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
43,CA-2017-139619,19/09/17,Standard Class,Erin Smith,Corporate,Melbourne,Florida,South,Office Supplies,Phones,95.616,2,9.5616
97,CA-2017-157833,17/06/17,First Class,Katherine Ducich,Consumer,San Francisco,California,West,Office Supplies,Phones,51.312,3,17.9592
98,CA-2016-149223,06/09/16,Standard Class,Elpida Rittenbach,Corporate,Saint Paul,Minnesota,Central,Office Supplies,Phones,77.880,6,22.5852
225,CA-2015-163055,09/08/15,Standard Class,David Smith,Corporate,Detroit,Michigan,Central,Office Supplies,Phones,2.200,1,0.9680

In [139]:
df

,Order ID,Order Date,Ship Mode,Customer Name,Segment,City,State,Region,Category,Sub-Category,Sales,Quantity,Profit
0,CA-2016-152156,08/11/16,Second Class,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Phones,261.9600,2,41.9136
1,CA-2016-152156,08/11/16,Second Class,Claire Gute,Consumer,Henderson,Kentucky,South,Furniture,Phones,731.9400,3,219.5820
2,CA-2016-138688,12/06/16,Second Class,Darrin Van Huff,Corporate,Los Angeles,California,West,Office Supplies,Phones,14.6200,2,6.8714
3,US-2015-108966,11/10/15,Standard Class,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Furniture,Phones,957.5775,5,-383.0310
4,US-2015-108966,11/10/15,Standard Class,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Phones,22.3680,2,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2014-110422,21/01/14,Second Class,Tom Boeckenhauer,Consumer,Miami,Florida,South,Furniture,Phones,25.2480,3,4.1028
9990,CA-2017-121258,26/02/17,Standard Class,Dave Brooks,Consumer,Costa Mesa,California,West,Furniture,Phones,91.9600,2,15.6332
9991,CA-2017-121258,26/02/17,Standard Class,Dave Brooks,Consumer,Costa Mesa,California,West,Technology,Phones,258.5760,2,19.3932
9992,CA-2017-121258,26/02/17,Standard Class,Dave Brooks,Consumer,Costa Mesa,California,West,Office Supplies,Phones,29.6000,4,13.3200
9993,CA-2017-119914,04/05/17,Second Class,Chris Cortes,Consumer,Westminster,California,West,Office Supplies,Phones,243.1600,2,72.9480

In [142]:
df.groupby(by="Region")

In [144]:
df.groupby(by="Region")['Sales'].sum()

Region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

In [146]:
df.groupby(by="Region")[["Sales","Quantity"]].sum()

               Sales  Quantity
Region
Central  501239.8908      8780
East     678781.2400     10618
South    391721.9050      6209
West     725457.8245     12266